// Mock data for demo mode - no external services needed

export const DEMO_COMPETITORS = [
  {
    id: '1',
    name: 'Nike',
    domain: 'nike.com',
    homepage_url: 'https://nike.com',
    scrape_status: 'active',
    email_subscribed: true,
    last_scraped_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '2',
    name: 'Adidas',
    domain: 'adidas.com',
    homepage_url: 'https://adidas.com',
    scrape_status: 'active',
    email_subscribed: true,
    last_scraped_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '3',
    name: 'Lululemon',
    domain: 'lululemon.com',
    homepage_url: 'https://lululemon.com',
    scrape_status: 'active',
    email_subscribed: false,
    last_scraped_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '4',
    name: 'Under Armour',
    domain: 'underarmour.com',
    homepage_url: 'https://underarmour.com',
    scrape_status: 'error',
    email_subscribed: true,
    last_scraped_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const DEMO_PROMOS = [
  {
    id: 'p1',
    competitor_id: '1',
    competitor_name: 'Nike',
    competitor_domain: 'nike.com',
    promo_text: 'Up to 50% off select styles. Limited time only.',
    discount_percent: 50,
    promo_code: 'SAVE50',
    source_type: 'announcement_bar',
    first_seen_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    last_seen_at: new Date().toISOString(),
    is_active: true,
  },
  {
    id: 'p2',
    competitor_id: '2',
    competitor_name: 'Adidas',
    competitor_domain: 'adidas.com',
    promo_text: 'Free shipping on orders over $50',
    discount_percent: null,
    promo_code: null,
    source_type: 'announcement_bar',
    first_seen_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    last_seen_at: new Date().toISOString(),
    is_active: true,
  },
  {
    id: 'p3',
    competitor_id: '3',
    competitor_name: 'Lululemon',
    competitor_domain: 'lululemon.com',
    promo_text: 'Boxing Week Sale: Extra 20% off We Made Too Much',
    discount_percent: 20,
    promo_code: 'BOXING20',
    source_type: 'hero_banner',
    first_seen_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    last_seen_at: new Date().toISOString(),
    is_active: true,
  },
  {
    id: 'p4',
    competitor_id: '1',
    competitor_name: 'Nike',
    competitor_domain: 'nike.com',
    promo_text: 'Members get 25% off full-price items',
    discount_percent: 25,
    promo_code: 'MEMBER25',
    source_type: 'hero_banner',
    first_seen_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    last_seen_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    is_active: false,
  },
];

export const DEMO_EMAILS = [
  {
    id: 'e1',
    competitor_id: '1',
    competitor_name: 'Nike',
    competitor_domain: 'nike.com',
    subject: '🎁 Your exclusive 30% off is waiting',
    campaign_type: 'promo',
    promo_code: 'HOLIDAY30',
    discount_percent: 30,
    received_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'e2',
    competitor_id: '2',
    competitor_name: 'Adidas',
    competitor_domain: 'adidas.com',
    subject: 'New Arrivals: The Ultraboost 24 is here',
    campaign_type: 'new_arrival',
    promo_code: null,
    discount_percent: null,
    received_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'e3',
    competitor_id: '3',
    competitor_name: 'Lululemon',
    competitor_domain: 'lululemon.com',
    subject: 'This week: What we\'re loving',
    campaign_type: 'newsletter',
    promo_code: null,
    discount_percent: null,
    received_at: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'e4',
    competitor_id: '1',
    competitor_name: 'Nike',
    competitor_domain: 'nike.com',
    subject: 'Flash Sale: 40% off ends tonight',
    campaign_type: 'promo',
    promo_code: 'FLASH40',
    discount_percent: 40,
    received_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const DEMO_ALERTS = [
  {
    id: 'a1',
    alert_type: 'new_promo',
    title: 'Nike launched a new promo',
    message: 'Up to 50% off select styles. Limited time only.',
    competitor: { id: '1', name: 'Nike', domain: 'nike.com' },
    metadata: { discount_percent: 50, promo_code: 'SAVE50' },
    is_read: false,
    created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: 'a2',
    alert_type: 'email_spike',
    title: 'Adidas is sending more emails than usual',
    message: '5 emails today vs 1.2 daily average',
    competitor: { id: '2', name: 'Adidas', domain: 'adidas.com' },
    metadata: { today_count: 5, weekly_average: 1.2 },
    is_read: false,
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'a3',
    alert_type: 'promo_ended',
    title: 'Nike\'s promo has ended',
    message: 'Promotion no longer detected: "Members get 25% off"',
    competitor: { id: '1', name: 'Nike', domain: 'nike.com' },
    metadata: {},
    is_read: true,
    created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const DEMO_FEED = [
  ...DEMO_PROMOS.map((p) => ({
    id: p.id,
    event_type: 'promo' as const,
    competitor_name: p.competitor_name,
    competitor_domain: p.competitor_domain,
    title: p.promo_text,
    code: p.promo_code,
    discount_percent: p.discount_percent,
    source_type: p.source_type,
    event_time: p.first_seen_at,
    is_active: p.is_active,
  })),
  ...DEMO_EMAILS.map((e) => ({
    id: e.id,
    event_type: 'email' as const,
    competitor_name: e.competitor_name,
    competitor_domain: e.competitor_domain,
    title: e.subject,
    code: e.promo_code,
    discount_percent: e.discount_percent,
    source_type: e.campaign_type,
    event_time: e.received_at,
    is_active: true,
  })),
].sort((a, b) => new Date(b.event_time).getTime() - new Date(a.event_time).getTime());

export const DEMO_ORG = {
  id: 'demo-org',
  name: 'Demo Company',
  email: 'demo@example.com',
  plan_tier: 'growth',
  competitor_limit: 15,
  email_subdomain: 'demo-abc123',
  subscription_status: 'active',
};
